export const FETCH_LATEST_LISTING = "FETCH_LATEST_LISTING";
export const FETCH_LATEST_LISTING_SUCCESS = "FETCH_LATEST_LISTING_SUCCESS";
export const FETCH_LATEST_LISTING_FAILURE = "FETCH_LATEST_LISTING_FAILURE";
export const LIMIT_LATEST_LISTING = "LIMIT_LATEST_LISTING";
